name: Horve
author: SantEnnio
category: Interface
tags: [Fx.Scroll, Horizontal]
docs: http://eqepa.com/projects/mootools-plugins/horve-mootools-horizontal-vertical-scroll-websites/
demo: http://eqepa.com/Playground/Mootools/Horve/0.4plus/Example/demo.html
current: 0.4.1