name: Horve
author: SantEnnio
category: Interface
tags: [Fx.Scroll, Horizontal]
docs: http://www.enniopirolo.name/projects/mootools-projects/horve/
demo: http://enniopirolo.name/demos/horve/Example/demo.html
current: 0.5